uint32 test

int32 rHand_tactileCmd

# torsoMotorCurrentCommand
# headPanMotorCurrentCommand
# headTiltMotorCurrentCommand
float64 tMotor_i
float64 hpMotor_i
float64 htMotor_i

# headPanMotorPositionCommand
# headTiltMotorPositionCommand
float64 hpMotor_q
float64 htMotor_q

# headPanMotorVelocityCommand
# headTiltMotorVelocityCommand
float64 hpMotor_dq
float64 htMotor_dq

VelmaLowLevelCommandArm lArm
VelmaLowLevelCommandArm rArm

VelmaLowLevelCommandHand lHand
VelmaLowLevelCommandHand rHand

