uint32 test

VelmaLowLevelCommandSimple rTact
bool rTact_valid

VelmaLowLevelCommandMotor tMotor
bool tMotor_valid

VelmaLowLevelCommandMotor hpMotor
bool hpMotor_valid

VelmaLowLevelCommandMotor htMotor
bool htMotor_valid

VelmaLowLevelCommandArm lArm
bool lArm_valid

VelmaLowLevelCommandArm rArm
bool rArm_valid

VelmaLowLevelCommandSimple lArmFri
bool lArmFri_valid

VelmaLowLevelCommandSimple rArmFri
bool rArmFri_valid

VelmaLowLevelCommandHand lHand
bool lHand_valid

VelmaLowLevelCommandHand rHand
bool rHand_valid

