JntLimit:
  joint_names: [torso_0_joint, right_arm_0_joint, right_arm_1_joint, right_arm_2_joint, right_arm_3_joint, right_arm_4_joint, right_arm_5_joint, right_arm_6_joint, left_arm_0_joint, left_arm_1_joint, left_arm_2_joint, left_arm_3_joint, left_arm_4_joint, left_arm_5_joint, left_arm_6_joint]
  limits_0: [-1.56, 1.56]
  limits_1: [-2.96, 2.96]
  limits_2: [-2.09, -0.2, 0.2, 2.09]
  limits_3: [-2.96, 2.96]
  limits_4: [-2.095, -0.2, 0.2, 2.095]
  limits_5: [-2.96, 2.96]
  limits_6: [-2.09, -0.2, 0.2, 2.09]
  limits_7: [-2.96, 2.96]
  limits_8: [-2.96, 2.96]
  limits_9: [-2.09, -0.2, 0.2, 2.09]
  limits_10: [-2.96, 2.96]
  limits_11: [-2.09, -0.2, 0.2, 2.09]
  limits_12: [-2.96, 2.96]
  limits_13: [-2.09, -0.2, 0.2, 2.09]
  limits_14: [-2.96, 2.96]
  limit_range: [0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26, 0.26]
  max_trq: [10.0, 10.0, 10.0, 10.0, 10.0, 10.0, 6.0, 6.0, 10.0, 10.0, 10.0, 10.0, 10.0, 6.0, 6.0]
