#!/usr/bin/env python

## Resets shared memory for IPC for Velma system.
# @ingroup utilities
# @file reset_shm_comm
# @namespace scripts.reset_shm_comm Resets shared memory for IPC for Velma system.

import roslib; roslib.load_manifest('velma_common')
import subprocess

if __name__ == "__main__":

    shm_files = [
        'EC_Command_data',
        'EC_Command_hdr',
        'EC_Status_data',
        'EC_Status_hdr',
        'lLwr_cmd_data',
        'lLwr_cmd_hdr',
        'lLwr_st_data',
        'lLwr_st_hdr',
        'rLwr_cmd_data',
        'rLwr_cmd_hdr',
        'rLwr_st_data',
        'rLwr_st_hdr',
        'velma_core_cs_task_cs_cmd_data',
        'velma_core_cs_task_cs_cmd_hdr',
        'velma_core_cs_task_cs_st_data',
        'velma_core_cs_task_cs_st_hdr',
        'velma_core_cs_ve_body_cmd_data',
        'velma_core_cs_ve_body_cmd_hdr',
        'velma_core_cs_ve_body_st_data',
        'velma_core_cs_ve_body_st_hdr',
        'velma_core_cs_pred_ctrl_cmd_data',
        'velma_core_cs_pred_ctrl_cmd_hdr',
        'velma_core_cs_pred_ctrl_st_data',
        'velma_core_cs_pred_ctrl_st_hdr',
    ]

    for file_name in shm_files:
        print 'rm /dev/shm/' + file_name
        subprocess.call(['rm', '/dev/shm/' + file_name])

    print "Cleanup done."
    print "You can now run the control system of Velma."
