#!/usr/bin/env python

## Resets shared memory for IPC for Velma system.
# @ingroup utilities
# @file reset_shm_comm
# @namespace scripts.reset_shm_comm Resets shared memory for IPC for Velma system.

import roslib; roslib.load_manifest('velma_common')
import subprocess

if __name__ == "__main__":

    print 'rm /dev/shm/*'
    subprocess.call(['rm', '/dev/shm/*'])
