CommandCartImpTrjImp imp        # subsystem_buffer{type: port; data_type: CommandCartImpTrjImp; validity: imp_valid}
bool imp_valid

CommandCartImpTrjPose pose      # subsystem_buffer{type: port; data_type: CommandCartImpTrjPose; validity: pose_valid}
bool pose_valid

CommandCartImpTrjPose tool      # subsystem_buffer{type: port; data_type: CommandCartImpTrjPose; validity: tool_valid}
bool tool_valid

# TODO: check if this msg is complete

