CommandCartImp cart_r
bool cart_r_valid

CommandCartImp cart_l
bool cart_l_valid

CommandJntImp jnt
bool jnt_valid

CommandHead head
bool head_valid

bool safe_col
bool safe_col_valid

barrett_hand_msgs/CommandHand handRight
bool handRight_valid

bool handRightReset
bool handRightReset_valid

barrett_hand_msgs/CommandHand handLeft
bool handLeft_valid

bool handLeftReset
bool handLeftReset_valid

CommandServo hp
bool hp_valid

CommandServo ht
bool ht_valid

CommandServo t
bool t_valid

bool objectGraspedRight
bool objectGraspedRight_valid

bool objectGraspedLeft
bool objectGraspedLeft_valid

uint32 identificationMeasurementRightCmd
bool identificationMeasurementRightCmd_valid

uint32 identificationMeasurementLeftCmd
bool identificationMeasurementLeftCmd_valid
