CommandCartImp cart_r

CommandCartImp cart_l

CommandJntImp jnt
bool jnt_valid

CommandHead head
bool head_valid

CommandJntImpTrapez jnt_trapez
bool jnt_trapez_valid

CommandHeadTrapez head_trapez
bool head_trapez_valid

bool safe_col
bool safe_col_valid

barrett_hand_msgs/CommandHand handRight
bool handRight_valid

bool handRightReset
bool handRightReset_valid

barrett_hand_msgs/CommandHand handLeft
bool handLeft_valid

bool handLeftReset
bool handLeftReset_valid

CommandServo hp

CommandServo ht

CommandServo t

