uint32 test

VelmaLowLevelCommandSimple rTact
bool rTact_valid

VelmaLowLevelCommandMotor tMotor
bool tMotor_valid

VelmaLowLevelCommandMotor hpMotor
bool hpMotor_valid

VelmaLowLevelCommandMotor htMotor
bool htMotor_valid

VelmaLowLevelCommandArm lArm
bool lArm_valid

VelmaLowLevelCommandArm rArm
bool rArm_valid

VelmaLowLevelCommandHand lHand
bool lHand_valid

VelmaLowLevelCommandHand rHand
bool rHand_valid

VelmaLowLevelCommandSimple sc
bool sc_valid

