uint32 test

VelmaLowLevelStatusSC sc
bool sc_valid

VelmaLowLevelStatusArm rArm
bool rArm_valid

VelmaLowLevelStatusArm lArm
bool lArm_valid

VelmaLowLevelStatusHand rHand
bool rHand_valid

VelmaLowLevelStatusHand lHand
bool lHand_valid

VelmaLowLevelStatusFT rFt
bool rFt_valid

VelmaLowLevelStatusFT lFt
bool lFt_valid

VelmaLowLevelStatusMotor tMotor
bool tMotor_valid

VelmaLowLevelStatusMotor hpMotor
bool hpMotor_valid

VelmaLowLevelStatusMotor htMotor
bool htMotor_valid

barrett_hand_controller_msgs/BHPressureState rHand_p
bool rHand_p_valid

geometry_msgs/Wrench[3] lHand_f
bool lHand_f_valid

