uint32 test
bool test_valid

float64 tMotor_i
bool tMotor_i_valid

bool tMotor_enable
bool tMotor_enable_valid

CommandArm lArm
bool lArm_valid

CommandArm rArm
bool rArm_valid

CommandMotor hpMotor
bool hpMotor_valid

CommandMotor htMotor
bool htMotor_valid

int32 sc
bool sc_valid

int32 tact
bool tact_valid

barrett_hand_msgs/CommandHand lHand
bool lHand_valid

bool lHandReset
bool lHandReset_valid

barrett_hand_msgs/CommandHand rHand
bool rHand_valid

bool rHandReset
bool rHandReset_valid

