uint32 test
bool test_valid

StatusSC sc
bool sc_valid

StatusArm rArm
bool rArm_valid

StatusArm lArm
bool lArm_valid

StatusFT rFt
bool rFt_valid

StatusFT lFt
bool lFt_valid

StatusMotor tMotor
bool tMotor_valid

StatusMotor hpMotor
bool hpMotor_valid

StatusMotor htMotor
bool htMotor_valid

barrett_hand_msgs/StatusHand rHand
bool rHand_valid

barrett_hand_msgs/StatusHand lHand
bool lHand_valid

barrett_hand_status_msgs/BHPressureState p
bool p_valid

geometry_msgs/Wrench[3] f
bool f_valid

