#!/usr/bin/env python

import sys

from rqt_velma.my_module import VelmaControlPanelPlugin
from rqt_gui.main import Main

plugin = 'rqt_velma'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
